In [41]:
import statsmodels.stats.inter_rater as stats
from glob import glob
import pandas as pd
import numpy as np

In [42]:
def merge_annotations(input_glob : str):
    dfs = [pd.read_json(path, lines=True) for path in glob(input_glob)]
    results = np.empty((dfs[0].shape[0], len(dfs)), np.int32)
    print(results.shape)
    for x, df in enumerate(dfs):
        for y, row in df.iterrows():
            labels = set(row['label'])
            if labels == {'Off Topic'}:
                results[y,x] = 0
            if labels == {'On Topic', 'Neutral'}:
                results[y,x] = 1
            if labels == {'On Topic', 'Con'}:
                results[y,x] = 2
            if labels == {'On Topic', 'Pro'}:
                results[y,x] = 3
    return results


annotations = merge_annotations('annotations/*.jsonl')
aggregated, _ = stats.aggregate_raters(annotations)

(1805, 3)


In [43]:
print(aggregated)

[[3 0 0 0]
 [0 0 1 2]
 [0 1 2 0]
 ...
 [1 2 0 0]
 [0 2 1 0]
 [1 2 0 0]]


In [44]:
stats..fleiss_kappa(aggregated, 'fleiss')

0.36667538475512645

In [45]:
1.0 * np.asarray(aggregated)

array([[3., 0., 0., 0.],
       [0., 0., 1., 2.],
       [0., 1., 2., 0.],
       ...,
       [1., 2., 0., 0.],
       [0., 2., 1., 0.],
       [1., 2., 0., 0.]])